name: Build, pack and publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Check out
        uses: actions/checkout@v3

      - name: Build
        run: dotnet build 'DIAttributes/Mdk.DIAttributes.csproj' --configuration Release

      - name: Package
        run: dotnet pack 'DIAttributes/Mdk.DIAttributes.csproj' --configuration Release --output publish_folder

      - name: Publish
        run: dotnet nuget push publish_folder/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
